# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://SI-NZ-workshop-2024.github.io
title: The 2nd SI^NZ Workshop on Software Engineering
email: 
author: SI^NZ
description: 
copyright: 'Copyright &copy; 2024 SI^NZ. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SoftwareInnovNZ
